# Generated by Django 2.0.3 on 2018-05-01 09:18

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', markdownx.models.MarkdownxField()),
                ('header', models.ImageField(upload_to='projet/img/upload/')),
            ],
        ),
    ]
