# Generated by Django 2.0.3 on 2018-08-06 18:30

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('a_propos', markdownx.models.MarkdownxField(default='')),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', markdownx.models.MarkdownxField()),
                ('header', models.ImageField(upload_to='projet/img/upload/')),
                ('etat', models.BooleanField(default=False, verbose_name='Terminé ?')),
                ('phare', models.BooleanField(default=False, verbose_name='Projet Phare ?')),
                ('adulte', models.BooleanField(default=False, verbose_name='Adulte ?')),
                ('couleur_tab_texte', models.CharField(blank=True, default='#d500f9', max_length=7)),
                ('couleur_tab_active_background', models.CharField(blank=True, default='#f3e5f5', max_length=7)),
                ('couleur_tab_soulignement', models.CharField(blank=True, default='#4a148c', max_length=7)),
                ('app_name', models.CharField(max_length=20)),
                ('app_is_create', models.BooleanField(default=False)),
                ('chef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Membre', verbose_name='chef de projet')),
                ('codeur', models.ManyToManyField(blank=True, related_name='codeur', to='core.Membre', verbose_name='Codeur(s)')),
                ('graphiste', models.ManyToManyField(blank=True, related_name='graphiste', to='core.Membre', verbose_name='Graphiste(s)')),
                ('musicien', models.ManyToManyField(blank=True, related_name='musicien', to='core.Membre', verbose_name='Musicien(s)')),
                ('scenariste', models.ManyToManyField(blank=True, related_name='scenariste', to='core.Membre', verbose_name='Scénariste(s)')),
            ],
        ),
    ]
