# Generated by Django 2.0.3 on 2018-05-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
