# Generated by Django 2.0.3 on 2018-05-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='app_is_create',
            field=models.BooleanField(default=False),
        ),
    ]
