# Generated by Django 2.0.3 on 2018-05-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180501_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='membres',
            field=models.ManyToManyField(to='core.Membre'),
        ),
    ]
