# Generated by Django 2.0.3 on 2018-05-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180501_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='core.Membre', verbose_name='groups'),
        ),
    ]
