# Generated by Django 2.0.3 on 2018-06-13 17:31

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projet_adulte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_propos', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
