# Generated by Django 2.0.3 on 2018-06-13 17:32

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='a_propos',
            field=markdownx.models.MarkdownxField(default=''),
        ),
    ]
