# Generated by Django 2.0.3 on 2018-05-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_projet_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='membres',
        ),
        migrations.AddField(
            model_name='projet',
            name='chef',
            field=models.ManyToManyField(related_name='chef', to='core.Membre', verbose_name='chef(s) de projet'),
        ),
        migrations.AddField(
            model_name='projet',
            name='codeur',
            field=models.ManyToManyField(related_name='codeur', to='core.Membre', verbose_name='Codeur(s)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='graphiste',
            field=models.ManyToManyField(related_name='graphiste', to='core.Membre', verbose_name='Graphiste(s)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='musicien',
            field=models.ManyToManyField(related_name='musicien', to='core.Membre', verbose_name='Musicien(s)'),
        ),
    ]
