# Generated by Django 2.0.3 on 2018-05-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180501_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='chef',
            field=models.ManyToManyField(blank=True, related_name='chef', to='core.Membre', verbose_name='chef(s) de projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='codeur',
            field=models.ManyToManyField(blank=True, related_name='codeur', to='core.Membre', verbose_name='Codeur(s)'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='graphiste',
            field=models.ManyToManyField(blank=True, related_name='graphiste', to='core.Membre', verbose_name='Graphiste(s)'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='musicien',
            field=models.ManyToManyField(blank=True, related_name='musicien', to='core.Membre', verbose_name='Musicien(s)'),
        ),
    ]
