# Generated by Django 2.0.3 on 2018-05-01 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180501_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='chef',
        ),
        migrations.AddField(
            model_name='projet',
            name='chef',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chef', to='core.Membre', verbose_name='chef(s) de projet'),
        ),
    ]
