# Generated by Django 2.0.3 on 2018-05-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180501_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='phare',
            field=models.BooleanField(default=False, verbose_name='Projet Phare ?'),
        ),
    ]
