# Generated by Django 2.0.3 on 2018-05-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_projet_phare'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='scenariste',
            field=models.ManyToManyField(blank=True, related_name='scenariste', to='core.Membre', verbose_name='Scénariste(s)'),
        ),
    ]
