# Generated by Django 2.0.3 on 2018-05-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180502_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='chef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chef', to='core.Membre', verbose_name='chef de projet'),
        ),
    ]
