# Generated by Django 2.0.3 on 2018-05-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180502_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='chef',
        ),
    ]
