# Generated by Django 2.0.3 on 2018-05-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_projet_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='chef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Membre', verbose_name='chef de projet'),
        ),
    ]
